#pragma once

template <class T>
class CProxy_ICustManageAppEvents : public IConnectionPointImpl<T, &__uuidof( _ICustManageAppEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
