#pragma once

template <class T>
class CProxy_IManagedAppBridgeEvents : public IConnectionPointImpl<T, &__uuidof( _IManagedAppBridgeEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
